shoppingwebsite/cart/urls.py
from . import views
from django.urls import path
app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('delete/<int:product_id>/', views.full_delete, name='full_delete'),
]

shoppingwebsite/searchapp/urls.py
from . import views
from django.urls import path
app_name = 'searchapp'

urlpatterns = [
    path('', views.searchapp, name='search_products'),
]

shoppingwebsite/shoppingapp/urls.py
from . import views
from django.urls import path
app_name = 'shoppingapp'

urlpatterns = [
    path('', views.allprodcat, name='allprodcat'),
    path('<slug:c_slug>/', views.allprodcat, name='products_by_category'),
    path('<slug:c_slug>/<slug:p_slug>/', views.product_details, name='product_details'),
]

shoppingwebsite/shoppingproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', include('searchapp.urls')),
    path('cart/', include('cart.urls')),
    path('', include('shoppingapp.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shoppingwebsite/cart/models.py
from django.db import models
from shoppingapp.models import Product

# Create your models here.


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ('date',)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

shoppingwebsite/searchapp/models.py
from django.db import models

# Create your models here.

shoppingwebsite/shoppingapp/models.py
from django.db import models

from django.urls import reverse

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    img = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shoppingapp:products_by_category', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shoppingapp:product_details', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.name

shoppingwebsite/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shoppingapp.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, cart=cart, quantity=1)
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    # no operation

    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_delete(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

shoppingwebsite/searchapp/views.py
from django.shortcuts import render
from shoppingapp.models import Product
from django.db.models import Q

# Create your views here.


def searchapp(request):
    if 'q' in request.GET:
        query = request.GET.get('q')
        if query == "":
            query = None
            products = None
            return render(request, 'search.html', {'query': query, 'products': products})
        else:
            products = Product.objects.all().filter(Q(name__contains=query) | Q(desc__contains=query))
            return render(request, 'search.html', {'query': query, 'products': products})

shoppingwebsite/shoppingapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage


# Create your views here.


def allprodcat(request, c_slug=None):
    c_page = None
    products =None
    if c_slug is not None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)

    paginator = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', 1))
        # to access clicking page number
    except():
        page = 1
    try:
        products = paginator.page(page)
    except(EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, "category.html", {'category': c_page, 'products': products})


def product_details(request, c_slug, p_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=p_slug)
    except Exception as e:
        raise e
    return render(request, "product.html", {'product': product})

shoppingwebsite/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" href="{% static 'img/logos.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;1,900&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
<div class="container">
{% include 'header.html' %}<br>
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
</body>
</html>

shoppingwebsite/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    This is a cart page. Proceed to review your items and place the order
{% endblock %}

{% block title %}
    Cart- Daily Store PVT LTD
{% endblock %}

{% block content %}
    {% if not cart_items %}
        <div>
            <div class="text-center"><br>
                <h1 class="text-center my_title">Your Shopping Cart is Empty</h1><br>
                <p>Please Click <a href="{% url 'shoppingapp:allprodcat' %}">Here</a>to Continue Shopping..</p>
            </div>
        </div>
    {% else %}
        <div>
            <div class="text-center"><br>
                <h1 class="text-center my_title">Your Shopping Cart</h1><br>
            </div>
            <div class="row mx-auto">
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <table class="table my_custom_table">
                        <thead class="my_custom_thead">
                        <tr>
                            <th colspan="5">Your Items</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for cart_item in cart_items %}
                        <tr>
                            <td>
                                <a href="{{ cart_item.product.get_url}}"><img src="{{ cart_item.product.img.url }}" alt="cart_item.product.name" class="float-left rounded custom_image" style="height: 100px;width: 100px;"></a>
                            </td>
                            <td class="text-lef">
                                {{ cart_item.product.name }}<br>
                                SKU: {{ cart_item.product.id }}<br>
                                Price: ₹ {{ cart_item.product.price }}<br>
                                Qty: {{ cart_item.quantity }} x ₹ {{ cart_item }}
                            </td>
                            <td>
                                ₹ {{ cart_item.sub_total }}
                            </td>
                            {% if cart_item.quantity < cart_item.product.stock %}
                            <td>
                                <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i></a>
                                &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                                &nbsp;<a href="{% url 'cart:full_delete' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                            </td>
                            {% else %}
                            <td>
                                &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                                &nbsp;<a href="{% url 'cart:full_delete' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                            </td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                    <table class="table my_custom_table">
                        <thead class="my_custom_thead">
                        <tr>
                            <th>
                                Checkout
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                Please review your cart items before proceeding with the order payment.
                            </td>
                        </tr>
                        <tr>
                            <td class="text-left">
                                Your Total is : <strong> ₹ {{ total }}</strong>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                    <div class="mx_auto">
                        <a href="{% url 'shoppingapp:allprodcat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>
                         <a href="{% url 'shoppingapp:allprodcat' %}" class="btn btn-secondary btn-block my_custom_button">Payments </a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

shoppingwebsite/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {% if category %}
    {{ category.desc|truncatewords:150 }}
    {% else %}
    Everything available here..
    {% endif %}
{% endblock %}

{% block title %}
    {% if category %}
    {{ category.name}} - Daily Store
    {% else %}
    Our New Collection...
    {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
    <div>
        <div class="row my_row_class">
            <div class="mx_auto">
                <p><a href="{% url 'shoppingapp:allprodcat' %}"> Our new Products collections </a></p>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="mx_auto">
        {% if category %}
            <img class="my_image" src="{{ category.img.url }}" alt="{{ category.name }}" style="height: 300px;">
            </div><br>
            <div>
                <h1 class="text-center my_title">{{ category.name }}</h1>
                <p class="text-justify">{{ category.desc }}</p>
            </div>
        {% else %}
            <div>
                <img class="my_image my_image_padding" src="{% static 'img/banners.png' %}" alt="Our Products">
            </div><br>
            <div>
                <h1 class="text-center my_title">Our Product Collections</h1>
                <p class="text-justify">Daily Store is an Indian multinational ecommerce company based in Kochi,India, which focuses on online selling of fresh vegetables,meat products and clothings.</p>
            </div>
        {% endif %}
    <div class="container">
        <div class="row mx_auto">
            {% for product in products.object_list %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-4 xol-lg-4">
                    <div class="card text-center" style="min-width: 18rem">
                        <a href="{{ product.get_url }}"><img class="card-img-top my_image" src="{{ product.img.url }}" alt="{{ product.name }}"></a>
                        <div class="card-body">
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.price }}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="mx_auto">
            {% if products.paginator.num_pages > 1 %}
                <hr>
                <div class="text-center">
                    {% for pg in products.paginator.page_range %}
                        <a href="?page={{ pg }}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{ pg }}</a>
                    {% endfor %}
                </div>
            {% endif %}
        </div><br>
    </div>
{% endblock %}

shoppingwebsite/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; Daily Store Pvt Ltd. All Right Reserved</p>
</div>

shoppingwebsite/templates/header.html
{% load static %}
<header>
    <div style="text-align: center;">
        <a href="{% url 'shoppingapp:allprodcat' %}"><img src="{% static 'img/logos.png' %}" alt="logo image" width="50px" height="50px"></a>
    </div>
</header>

shoppingwebsite/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shoppingapp:allprodcat' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shoppingapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shoppingapp:allprodcat' %}">All Products</a></li>
              {% for cat in links %}
            <li><a class="dropdown-item" href="{{ cat.get_url }}">{{ cat.name }}</a></li>
               {% endfor %}
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart"></i>{% if item_count > 0 %} ({{ item_count }}) {% endif %}</a>
        </li>
      </ul>
      <form class="d-flex" action="{% url 'searchapp:search_products' %}" method="get">
          {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

shoppingwebsite/templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    {{ product.desc|truncatewords:150 }}
{% endblock %}

{% block title %}
    {{ product.name}} - Daily Store
{% endblock %}

{% block content %}
<div class="row my_pro_row_class">
    <div class="mx_auto">
        <h6><a href="{% url 'shoppingapp:allprodcat' %}">Home</a> | <a href="{{ product.category.get_url }}">{{ product.category }}</a> | {{ product.name }}</h6>
    </div>
</div><br>

<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <div style="min-width: 18rem">
                <img src="{{ product.img.url }}" alt="{{ product.name }}">
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
            <h1 class="my_pro_title">{{ product.name }}</h1>
            <p>₹ {{ product.price }}</p>
            <p class="my_title">Product Description:</p>
            <p class="text-justify my_pro_text">{{ product.desc }}</p>
            {% if product.stock <= 0 %}
            <p class="text-justify my_pro_text"><b>Out of Stock</b></p>
            {% else %}
            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
            {% endif %}
            </div>
        </div>
    </div>
</div><br>
{% endblock %}

shoppingwebsite/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    We have large varieties of products.
{% endblock %}

{% block title %}
    Search
{% endblock %}

{% block content %}
<div>
<p class="text-center my_search_text">You have searched for: <b>"{{ query }}"</b></p>
</div>
    <div class="container">
        <div class="row mx_auto">
            {% for product in products %}
                <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-4 xol-lg-4">
                    <div class="card text-center" style="min-width: 18rem">
                        <a href="{{ product.get_url }}"><img class="card-img-top my_image" src="{{ product.img.url }}" alt="{{ product.name }}"></a>
                        <div class="card-body">
                            <h4>{{ product.name }}</h4>
                            <p>{{ product.price }}</p>
                        </div>
                    </div>
                </div>
            {% empty %}
                <div class="row mx_auto">
                    <p class="text-center my_search_text"><b> No results found</b></p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}